### PR TITLE
fix TLS for outlook discovery

### PR DESCRIPTION
**Pull request by benschhold**
will add `<Encryption>tls</Encryption>` to the response, MS outlook then will use starttls

### CODE REVIEW

**Comment by rseichter** [comment]
Hello Benjamin, sorry for the belated response. As stated in the project's readme file, I don't currently accept source code contributions. Nevertheless, I am interested in where you found references to the `Encryption` XML tag, which I do not see listed in Microsoft's own [POX format](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/pox-autodiscover-xml-elements-for-exchange) documentation?

**Comment by benschhold** [comment]
Hello, 
sorry for late answer, i was wondering why it didnt pick up TLS automaticly and found some posts mentioning the encryption tag, after more digging i discovererd this documentation:
http://interoperability.blob.core.windows.net/files/MS-OXDSCLI/%5BMS-OXDSCLI%5D.pdf
**2.2.4.1.1.2.6.22**

**Comment by rseichter** [comment]
This is a very interesting piece of information, and a quite recent description of Autodiscover to boot. Thanks for pointing this document out to me, I'll be sure to study it in more detail.

**Comment by rseichter** [comment]
@benschhold If have prepared a [developer release](https://test.pypi.org/project/automx2/2021.6.dev1/) which supports the Encryption XML element. I hope it works for you as it does for my tests. The change is a bit different from what you suggested, but nevertheless I'd like to mention you in the change logs if that's OK with you. Please let me know your full name in case you agree with being mentioned.

**Comment by rseichter** [comment]
Closing this pull request as it is superseded by release 2021.6.

**Pull request closed without merging**
